pipeline {
    agent any

    stages {
    //     stage('Clone') {
    //         steps {
    //             git 'https://github.com/sksahilhaque/java-crud-app.git'
    //         }
    //     }

        stage('Build') {
            steps {
                sh './build.sh'
            }
        }

        stage('Run with Input') {
            steps {
                sh 'java -cp out StudentManager < input.txt'
            }
        }

    }
}
