pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh '''
                    cd java-crud-app
                    chmod +x build.sh
                    ./build.sh
                '''
            }
        }

        stage('Run with Input') {
            steps {
                sh '''
                    cd java-crud-app
                    chmod +x run.sh
                    ./run.sh < input.txt > output.txt
                    '''
                    archiveArtifacts artifacts: 'java-crud-app/output.txt', fingerprint: true
                }
            }
    }
}
