pipeline {
    agent any

    stages {
    //     stage('Clone') {
    //         steps {
    //             git 'https://github.com/sksahilhaque/java-crud-app.git'
    //         }
    //     }

        stage('Build') {
            steps {
                  sh 'pwd'
                  sh 'ls -l java-crud-app'
                  sh 'cat build.sh || echo "build.sh missing"'
            }
        }

        stage('Run with Input') {
            steps {
                sh 'java -cp out StudentManager < input.txt'
            }
        }

    }
}
